# Generated by Django 5.0.6 on 2024-05-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxidriverapplication',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='taxidriverapplication',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='taxidriverapplication',
            name='id_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taxidriverapplication',
            name='insurance_proof',
            field=models.ImageField(upload_to='insurance_proofs/'),
        ),
        migrations.AlterField(
            model_name='taxidriverapplication',
            name='license_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taxidriverapplication',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taxidriverapplication',
            name='registration_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taxidriverapplication',
            name='vehicle_photo',
            field=models.ImageField(upload_to='vehicle_photos/'),
        ),
    ]
