# Generated by Django 5.0.4 on 2024-05-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactmessage',
            table='contactUs',
        ),
    ]
