# Generated by Django 5.0.6 on 2024-07-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedDriver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_make_model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20)),
                ('vehicle_photo', models.ImageField(upload_to='driver_photos/')),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
