# Generated by Django 5.0.6 on 2024-07-02 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('email_or_phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_class', models.CharField(max_length=20)),
                ('train_type', models.CharField(max_length=20)),
                ('from_station', models.CharField(max_length=100)),
                ('to_station', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('selected_seat', models.CharField(blank=True, max_length=10)),
                ('insurance', models.CharField(blank=True, max_length=50, null=True)),
                ('utilities', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_taxi', models.BooleanField(default=False)),
                ('child_traveler', models.BooleanField(default=False)),
                ('child_name', models.CharField(blank=True, max_length=100, null=True)),
                ('child_dob', models.DateField(blank=True, null=True)),
                ('drop_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pick_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='drivers.selecteddriver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='TaxiBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('taxi_date', models.DateField()),
                ('taxi_time', models.TimeField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_booking', to='booking.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.selecteddriver')),
            ],
        ),
    ]
