# Generated by Django 5.0.6 on 2024-06-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0002_remove_booking_taxi_remove_booking_train_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='000-000-0000', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_make_model', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('vehicle_photo', models.ImageField(upload_to='vehicle_photos/')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
