# Generated by Django 5.0.6 on 2024-06-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approveddriver',
            name='approved',
        ),
    ]
